default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.3
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --respect-gitignore]
        exclude: ".*poetry.lock|.*_static"
      # Run the formatter.
      - id: ruff-format
        args: [--respect-gitignore]
        exclude: ".*poetry.lock|.*_static"
