name: Ploomber Cloud

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-to-ploomber-cloud:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ploomber-cloud

      - name: Deploy
        env:
          PLOOMBER_CLOUD_KEY: ${{ secrets.PLOOMBER_CLOUD_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        run: |
          ploomber-cloud deploy --watch-incremental
        # The --watch-incremental flag will print deployment status and deployment
        # log updates to the GitHub logs.
        # To learn more, visit: https://docs.cloud.ploomber.io/en/latest/user-guide/github.html 
